# 2. 配置数据库连接相关的信息
spring:
  # Mybatis配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # serverTimezone=Asia/Shanghai 解决时区问题
    url: jdbc:mysql://localhost:3306/tbl_book?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:

# 3. 配置Mybatis-Plus相关信息
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
