# 配置端口
server:
  port: 9603

# 配置数据库和连接池
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tbl_book?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password:
  devtools:
    restart:
      # 设置不参与热部署的文件和文件夹（即修改后不重启）
      exclude: static/**,public/**,config/application.yml
      # 是否可用
      enabled: false

# 配置MP
mybatis-plus:
  global-config:
    db-config:
      # 表前缀
      table-prefix: tbl_
      # 数据库ID自增策略
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
